import unittest
import subprocess
import json
from collections import OrderedDict

from pdfscraper.models.sensor import Sensor
from pdfscraper.tests import test_utils


class TestWinsen(unittest.TestCase):

    def setUp(self):
        self.data = OrderedDict()
        self.incorrect_values = OrderedDict()

        test_utils.setUp(self.data, self.incorrect_values)

    def tearDown(self):
        test_utils.tearDown(self.data, self.incorrect_values)
        test_utils.display_result(self.incorrect_values)

        self.data.clear()
        self.incorrect_values.clear()

    def value_test(self, key, value, gas_number=1):
        test_utils.value_test(self.data, self.incorrect_values, key, value, gas_number)

    def test_ME2_CO(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/electrochemical-gas-sensor-me2-co.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME2-CO')
        self.value_test(Sensor.ALIAS, 'ME2-CO')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '2')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '200')
        self.value_test(Sensor.MAX_LOAD, '200')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '60')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1000')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '2000')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.015')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.031')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '50')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME2_O2_Ф20(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME2-O2-D20 0-25_ Manual (ver1.2).pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME2-O2-Ф20')
        self.value_test(Sensor.ALIAS, 'ME2-O2-Ф20')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '2')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '0')
        self.value_test(Sensor.MAX_HUMIDITY, '99')

        self.value_test(Sensor.MIN_LOAD, '10000')
        self.value_test(Sensor.MAX_LOAD, '10000')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Oxygen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O2')
        self.value_test(Sensor.UNITS, '%Vol')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '25')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '30')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.1')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.3')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'mA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '15')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_CH2O(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-CH2O 0-10ppm(Ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-CH2O')
        self.value_test(Sensor.ALIAS, 'ME3-CH2O')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '300')
        self.value_test(Sensor.MAX_LOAD, '300')
        self.value_test(Sensor.BIAS, '300')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Formaldehyde')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CH2O')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '10')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '5.8')
        self.value_test(Sensor.MAX_SENSITIVITY, '17.8')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_Cl2(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-Cl2 0-10ppm(Ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-Cl2')
        self.value_test(Sensor.ALIAS, 'ME3-Cl2')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Chlorine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'Cl2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '10')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.45')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.75')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_CO(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-CO 0-1000ppm(Ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-CO')
        self.value_test(Sensor.ALIAS, 'ME3-CO')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '36')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1000')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '2000')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.055')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.085')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '20')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_ETO(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-ETO 0-20ppm(Ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-ETO')
        self.value_test(Sensor.ALIAS, 'ME3-ETO')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, '300')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Ethylene Oxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'EtO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '1.5')
        self.value_test(Sensor.MAX_SENSITIVITY, '2.1')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '120')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_H2(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-H2 0-1000ppm(Ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-H2')
        self.value_test(Sensor.ALIAS, 'ME3-H2')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '90')
        self.value_test(Sensor.MAX_PRESSURE, '110')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '2')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1000')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '2000')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.005')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.015')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_H2S(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-H2S 0-100ppm(ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-H2S')
        self.value_test(Sensor.ALIAS, 'ME3-H2S')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '500')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.65')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.95')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_HCL(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-HCL 0-20ppm(Ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-HCL')
        self.value_test(Sensor.ALIAS, 'ME3-HCL')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Chloride')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HCL')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '200')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.4')
        self.value_test(Sensor.MAX_SENSITIVITY, '1.2')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_HF(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-HF 0-10ppm(Ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-HF')
        self.value_test(Sensor.ALIAS, 'ME3-HF')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '90')
        self.value_test(Sensor.MAX_PRESSURE, '110')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Fluoride')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HF')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '10')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.25')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.55')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_NH3(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-NH3 0-100ppm(ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-NH3')
        self.value_test(Sensor.ALIAS, 'ME3-NH3')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Ammonia')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '200')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.05')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.15')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_NO2(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-NO2 0-20ppm(ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-NO2')
        self.value_test(Sensor.ALIAS, 'ME3-NO2')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitrogen Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '150')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.36')
        self.value_test(Sensor.MAX_SENSITIVITY, '1.2')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '25')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_O3(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-O3 0-20ppm(Ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-O3')
        self.value_test(Sensor.ALIAS, 'ME3-O3')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Ozone')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.2')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.45')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.75')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '120')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ME3_SO2(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/winsen/ME3-SO2 0-20ppm(ver1.2) Manual.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Winsen')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ME3-SO2')
        self.value_test(Sensor.ALIAS, 'ME3-SO2')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Ozone')
        self.value_test(Sensor.GAS_EMPIRICAL, 'SO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '150')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.4')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.7')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)


if __name__ == '__main__':
    unittest.main()
