import unittest
from collections import OrderedDict

from pdfscraper.models.sensor import Sensor
from pdfscraper.tests import test_utils


class TestCityTech(unittest.TestCase):

    def setUp(self):
        self.data = OrderedDict()
        self.incorrect_values = OrderedDict()

        test_utils.setUp(self.data, self.incorrect_values)

    def tearDown(self):
        test_utils.tearDown(self.data, self.incorrect_values)
        test_utils.display_result(self.incorrect_values)

        self.data.clear()
        self.incorrect_values.clear()

    def value_test(self, key, value, gas_number=1):
        test_utils.value_test(self.data, self.incorrect_values, key, value, gas_number)

    def test_2CF3(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/2cf3.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AB231-801')
        self.value_test(Sensor.ALIAS, '2CF3')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '500')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '1000')
        self.value_test(Sensor.MIN_SENSITIVITY, '30')
        self.value_test(Sensor.MAX_SENSITIVITY, '70')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '17')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4CFPLUS(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4cf+.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '2112B2005')
        self.value_test(Sensor.ALIAS, '4CF+')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '5')
        self.value_test(Sensor.MAX_LOAD, '5')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '500')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '2000')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.055')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.085')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '20')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4CL(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4cl.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AH200-800')
        self.value_test(Sensor.ALIAS, '4CL')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '33')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Chlorine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'Cl2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '10')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.45')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.75')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4CM(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4cm.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '2112B2055R')
        self.value_test(Sensor.ALIAS, '4CM')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '55')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '5')
        self.value_test(Sensor.MAX_LOAD, '5')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '24')

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '2000')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '55')
        self.value_test(Sensor.MAX_SENSITIVITY, '85')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '10')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4ETO(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4eto.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AT204-800')
        self.value_test(Sensor.ALIAS, '4ETO')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, '300')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Ethylene Oxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'EtO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '1.4')
        self.value_test(Sensor.MAX_SENSITIVITY, '2.4')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '120')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4H(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4h.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AC200-800')
        self.value_test(Sensor.ALIAS, '4H')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '500')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.95')
        self.value_test(Sensor.MAX_SENSITIVITY, '1.45')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4HLM(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4hlm.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AC206-800')
        self.value_test(Sensor.ALIAS, '4HLM')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '500')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.95')
        self.value_test(Sensor.MAX_SENSITIVITY, '1.45')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4HN(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4hn.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AJ200-800')
        self.value_test(Sensor.ALIAS, '4HN')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, None)
        self.value_test(Sensor.DRIFT_INTERVAL, None)
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Cyanide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HCN')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '50')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '0.08')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.12')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '200')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4HSPLUS(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4hs+.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '2112B2025')
        self.value_test(Sensor.ALIAS, '4HS+')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '5')
        self.value_test(Sensor.MAX_LOAD, '5')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '20')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '500')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.55')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.85')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '20')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4HYT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4hyt.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AE204-803')
        self.value_test(Sensor.ALIAS, '4HYT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '2')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1000')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '2000')
        self.value_test(Sensor.MIN_SENSITIVITY, '5')
        self.value_test(Sensor.MAX_SENSITIVITY, '25')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4ND(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4ND.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AG200-800')
        self.value_test(Sensor.ALIAS, '4ND')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '33')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitrogen Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '150')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.45')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.75')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '25')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4NT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4NT.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AF4NT-800')
        self.value_test(Sensor.ALIAS, '4NT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, '300')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitric Oxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '250')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '1000')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.32')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.48')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '40')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4OxLL(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4oxllindustrialsafety.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AA783-33H')
        self.value_test(Sensor.ALIAS, '4OxLL')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4')
        self.value_test(Sensor.WEIGHT, '5.2')

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '60')
        self.value_test(Sensor.MIN_PRESSURE, '81.06')
        self.value_test(Sensor.MAX_PRESSURE, '121.59')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, '-600')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '60')
        self.value_test(Sensor.EXPECTED_LIFE, '60')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Oxygen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O2')
        self.value_test(Sensor.UNITS, '%Vol')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '25')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '30')
        self.value_test(Sensor.MIN_SENSITIVITY, '80')
        self.value_test(Sensor.MAX_SENSITIVITY, '130')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '15')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4PH_FAST(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4phfast.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'AP210-800')
        self.value_test(Sensor.ALIAS, '4PH-Fast')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Phosphine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'PH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.05')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '5')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '20')
        self.value_test(Sensor.MIN_SENSITIVITY, '1.4')
        self.value_test(Sensor.MAX_SENSITIVITY, '2')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4S_Rev_2(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4srev.2.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '2112B2015R')
        self.value_test(Sensor.ALIAS, '4S Rev. 2')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.1')
        self.value_test(Sensor.WEIGHT, '4.5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '81.06')
        self.value_test(Sensor.MAX_PRESSURE, '121.59')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Sulfur Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'SO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '150')
        self.value_test(Sensor.MIN_SENSITIVITY, '0.4')
        self.value_test(Sensor.MAX_SENSITIVITY, '0.6')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '25')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_4COSH(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/citytech/4cosh.pdf')

        self.value_test(Sensor.MANUFACTURER, 'CityTech')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ABC05-800')
        self.value_test(Sensor.ALIAS, '4COSH')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '10')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '30')
        self.value_test(Sensor.DRIFT_INTERVAL, '36')
        self.value_test(Sensor.EXPECTED_LIFE, '36')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 2)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '500')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, '1500')
        self.value_test(Sensor.MIN_SENSITIVITY, '50')
        self.value_test(Sensor.MAX_SENSITIVITY, '110')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '35')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide', gas_number=2)
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S', gas_number=2)
        self.value_test(Sensor.UNITS, 'ppm', gas_number=2)
        self.value_test(Sensor.RESOLUTION, '0.5', gas_number=2)
        self.value_test(Sensor.MIN_READING, '0', gas_number=2)
        self.value_test(Sensor.MAX_READING, '200', gas_number=2)
        self.value_test(Sensor.ZERO_CURRENT, None, gas_number=2)
        self.value_test(Sensor.OVERGAS_LIMIT, '500', gas_number=2)
        self.value_test(Sensor.MIN_SENSITIVITY, '500', gas_number=2)
        self.value_test(Sensor.MAX_SENSITIVITY, '1050', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_CONC, None, gas_number=2)
        self.value_test(Sensor.T_TEST, 't90', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE, '35', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_START, None, gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None, gas_number=2)
