import unittest
import subprocess
import json
from collections import OrderedDict

from pdfscraper.models.sensor import Sensor
from pdfscraper.tests import test_utils


class TestAlphasense(unittest.TestCase):

    def setUp(self):
        self.data = OrderedDict()
        self.incorrect_values = OrderedDict()

        test_utils.setUp(self.data, self.incorrect_values)

    def tearDown(self):
        test_utils.tearDown(self.data, self.incorrect_values)
        test_utils.display_result(self.incorrect_values)

        self.data.clear()
        self.incorrect_values.clear()

    def value_test(self, key, value, gas_number=1):
        test_utils.value_test(self.data, self.incorrect_values, key, value, gas_number)

    def test_SOH_A2(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/SOH-A2.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'SOH-A2')
        self.value_test(Sensor.ALIAS, 'SOH-A2')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '6')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 2)
        self.value_test(Sensor.GAS_NAME, 'Sulfur Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'SO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.2')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, '< ± 0.2')
        self.value_test(Sensor.OVERGAS_LIMIT, '50')
        self.value_test(Sensor.MIN_SENSITIVITY, '140')
        self.value_test(Sensor.MAX_SENSITIVITY, '250')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '10')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '15')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '10')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide', gas_number=2)
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S', gas_number=2)
        self.value_test(Sensor.UNITS, 'ppm', gas_number=2)
        self.value_test(Sensor.RESOLUTION, '0.1', gas_number=2)
        self.value_test(Sensor.MIN_READING, '0', gas_number=2)
        self.value_test(Sensor.MAX_READING, '100', gas_number=2)
        self.value_test(Sensor.ZERO_CURRENT, '± 0.25', gas_number=2)
        self.value_test(Sensor.OVERGAS_LIMIT, '200', gas_number=2)
        self.value_test(Sensor.MIN_SENSITIVITY, '450', gas_number=2)
        self.value_test(Sensor.MAX_SENSITIVITY, '900', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_CONC, '20', gas_number=2)
        self.value_test(Sensor.T_TEST, 't90', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE, '25', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_END, '20', gas_number=2)

    def test_SO2_AF(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/SO2AF.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'SO2-AF')
        self.value_test(Sensor.ALIAS, 'SO2-AF')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '4')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Sulfur Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'SO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '50')
        self.value_test(Sensor.ZERO_CURRENT, '< ± 0.6')
        self.value_test(Sensor.OVERGAS_LIMIT, '75')
        self.value_test(Sensor.MIN_SENSITIVITY, '300')
        self.value_test(Sensor.MAX_SENSITIVITY, '550')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '10')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '35')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '10')

    def test_SO2_A4(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/SO2A4.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'SO2-A4')
        self.value_test(Sensor.ALIAS, 'SO2-A4')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '15')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '36')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Sulfur Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'SO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '50')
        self.value_test(Sensor.ZERO_CURRENT, '-80 to 80')
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '320')
        self.value_test(Sensor.MAX_SENSITIVITY, '500')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '2')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '20')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '2')

    def test_SO2_AE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/SO2-AE.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'SO2-AE')
        self.value_test(Sensor.ALIAS, 'SO2-AE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '4')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Sulfur Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'SO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '1.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '2000')
        self.value_test(Sensor.ZERO_CURRENT, '< ±5')
        self.value_test(Sensor.OVERGAS_LIMIT, '10000')
        self.value_test(Sensor.MIN_SENSITIVITY, '50')
        self.value_test(Sensor.MAX_SENSITIVITY, '80')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '400')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '33')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '400')

    def test_PH3_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/PH3-A1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'PH3-A1')
        self.value_test(Sensor.ALIAS, 'PH3-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '20')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '33')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Phosphine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'PH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '10')
        self.value_test(Sensor.ZERO_CURRENT, '< ±0.5')
        self.value_test(Sensor.OVERGAS_LIMIT, '75')
        self.value_test(Sensor.MIN_SENSITIVITY, '550')
        self.value_test(Sensor.MAX_SENSITIVITY, '900')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '11')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '25')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '5')

    def test_OX_A431(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/OXA431.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'OX-A431')
        self.value_test(Sensor.ALIAS, 'OX-A431')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '85')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '-40')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 2)
        self.value_test(Sensor.GAS_NAME, 'Ozone')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, '-70 to 70')
        self.value_test(Sensor.OVERGAS_LIMIT, '50')
        self.value_test(Sensor.MIN_SENSITIVITY, '-200')
        self.value_test(Sensor.MAX_SENSITIVITY, '-650')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '1')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '45')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '1')

        self.value_test(Sensor.GAS_NAME, 'Nitrogen Dioxide', gas_number=2)
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO2', gas_number=2)
        self.value_test(Sensor.UNITS, 'ppm', gas_number=2)
        self.value_test(Sensor.RESOLUTION, None, gas_number=2)
        self.value_test(Sensor.MIN_READING, '0', gas_number=2)
        self.value_test(Sensor.MAX_READING, '20', gas_number=2)
        self.value_test(Sensor.ZERO_CURRENT, '-70 to 70', gas_number=2)
        self.value_test(Sensor.OVERGAS_LIMIT, '50', gas_number=2)
        self.value_test(Sensor.MIN_SENSITIVITY, '-200', gas_number=2)
        self.value_test(Sensor.MAX_SENSITIVITY, '-550', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_CONC, '2', gas_number=2)
        self.value_test(Sensor.T_TEST, 't90', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE, '45', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_END, '1', gas_number=2)

    def test_O2_A2(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/O2A2.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'O2-A2')
        self.value_test(Sensor.ALIAS, 'O2-A2')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.3')
        self.value_test(Sensor.HEIGHT, '17.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '16')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '55')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '5')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '47')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '1')
        self.value_test(Sensor.DRIFT_INTERVAL, '3')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Oxygen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O2')
        self.value_test(Sensor.UNITS, '%Vol')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '25')
        self.value_test(Sensor.ZERO_CURRENT, '< 2.5')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '80')
        self.value_test(Sensor.MAX_SENSITIVITY, '120')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA')
        self.value_test(Sensor.SENSITIVITY_CONC, '20.9')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '15')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '20.9')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '0')

    def test_O2_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/O2A1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'O2-A1')
        self.value_test(Sensor.ALIAS, 'O2-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.3')
        self.value_test(Sensor.HEIGHT, '17.4')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '16')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '55')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '5')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '47')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '1')
        self.value_test(Sensor.DRIFT_INTERVAL, '3')
        self.value_test(Sensor.EXPECTED_LIFE, '12')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Oxygen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O2')
        self.value_test(Sensor.UNITS, '%Vol')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '25')
        self.value_test(Sensor.ZERO_CURRENT, '< 2.5')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '190')
        self.value_test(Sensor.MAX_SENSITIVITY, '240')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA')
        self.value_test(Sensor.SENSITIVITY_CONC, '20.9')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '15')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '20.9')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '0')

    def test_NO_AE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/NOAE.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'NO-AE')
        self.value_test(Sensor.ALIAS, 'NO-AE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, '300')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, None)
        self.value_test(Sensor.DRIFT_INTERVAL, None)
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitrogen Oxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '5000')
        self.value_test(Sensor.ZERO_CURRENT, '0 to 15')
        self.value_test(Sensor.OVERGAS_LIMIT, '10000')
        self.value_test(Sensor.MIN_SENSITIVITY, '40')
        self.value_test(Sensor.MAX_SENSITIVITY, '80')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '250')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '75')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '250')

    def test_NO_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/NOA1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'NO-A1')
        self.value_test(Sensor.ALIAS, 'NO-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.45')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, '300')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitrogen Oxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.2')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '250')
        self.value_test(Sensor.ZERO_CURRENT, '0 to +2')
        self.value_test(Sensor.OVERGAS_LIMIT, '800')
        self.value_test(Sensor.MIN_SENSITIVITY, '320')
        self.value_test(Sensor.MAX_SENSITIVITY, '480')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '50')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '45')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '50')

    def test_NO2_A43F(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/NO2A43F.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'NO2-A43F')
        self.value_test(Sensor.ALIAS, 'NO2-A43F')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '85')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '-40')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitrogen Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, '-60 to +70')
        self.value_test(Sensor.OVERGAS_LIMIT, '50')
        self.value_test(Sensor.MIN_SENSITIVITY, '-175')
        self.value_test(Sensor.MAX_SENSITIVITY, '-450')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '2')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '2')

    def test_NO2_AE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/NO2-AE.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'NO2-AE')
        self.value_test(Sensor.ALIAS, 'NO2-AE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '33')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitrogen Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '200')
        self.value_test(Sensor.ZERO_CURRENT, '< ± 1.5')
        self.value_test(Sensor.OVERGAS_LIMIT, '1000')
        self.value_test(Sensor.MIN_SENSITIVITY, '-70')
        self.value_test(Sensor.MAX_SENSITIVITY, '-170')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '10')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '40')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '10')

    def test_NO2_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/NO2-A1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'NO2-A1')
        self.value_test(Sensor.ALIAS, 'NO2-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '33')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '-40')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitrogen Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.02')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, '< ± 0.4')
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '-250')
        self.value_test(Sensor.MAX_SENSITIVITY, '-650')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '10')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '50')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '10')

    def test_NO_A4(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/NO-A4.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'NO-A4')
        self.value_test(Sensor.ALIAS, 'NO-A4')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '85')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, '200')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '-20')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Nitrogen Oxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, '10 to 80')
        self.value_test(Sensor.OVERGAS_LIMIT, '50')
        self.value_test(Sensor.MIN_SENSITIVITY, '350')
        self.value_test(Sensor.MAX_SENSITIVITY, '550')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '2')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '25')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '2')

    def test_LFO2_A4(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/LFO2A4.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'LFO2-A4')
        self.value_test(Sensor.ALIAS, 'LFO2-A4')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '5')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, '-600')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '1')
        self.value_test(Sensor.DRIFT_INTERVAL, '3')
        self.value_test(Sensor.EXPECTED_LIFE, '48')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Oxygen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O2')
        self.value_test(Sensor.UNITS, '%Vol')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '25')
        self.value_test(Sensor.ZERO_CURRENT, None)
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '80')
        self.value_test(Sensor.MAX_SENSITIVITY, '130')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'μA')
        self.value_test(Sensor.SENSITIVITY_CONC, '20.9')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '17')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '20.9')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '0')

    def test_HCN_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/HCN-A1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'HCN-A1')
        self.value_test(Sensor.ALIAS, 'HCN-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '33')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, None)
        self.value_test(Sensor.DRIFT_INTERVAL, None)
        self.value_test(Sensor.EXPECTED_LIFE, '12')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Cyanide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HCN')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.05')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '< ±2')
        self.value_test(Sensor.OVERGAS_LIMIT, '150')
        self.value_test(Sensor.MIN_SENSITIVITY, '55')
        self.value_test(Sensor.MAX_SENSITIVITY, '85')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '30')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '70')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '30')

    def test_HCL_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/HCL-A1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'HCL-A1')
        self.value_test(Sensor.ALIAS, 'HCL-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '33')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, None)
        self.value_test(Sensor.DRIFT_INTERVAL, None)
        self.value_test(Sensor.EXPECTED_LIFE, None)
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Chloride')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HCl')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '< ±2.5')
        self.value_test(Sensor.OVERGAS_LIMIT, '200')
        self.value_test(Sensor.MIN_SENSITIVITY, '80')
        self.value_test(Sensor.MAX_SENSITIVITY, '130')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '25')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '300')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '25')

    def test_H2S_AH(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/H2SAH.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'H2S-AH')
        self.value_test(Sensor.ALIAS, 'H2S-AH')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '2')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.03')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '50')
        self.value_test(Sensor.ZERO_CURRENT, '< ± 0.2')
        self.value_test(Sensor.OVERGAS_LIMIT, '250')
        self.value_test(Sensor.MIN_SENSITIVITY, '950')
        self.value_test(Sensor.MAX_SENSITIVITY, '1450')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '20')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '20')

    def test_H2S_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/H2SA1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'H2S-A1')
        self.value_test(Sensor.ALIAS, 'H2S-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '3')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.05')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '< ± 0.4')
        self.value_test(Sensor.OVERGAS_LIMIT, '500')
        self.value_test(Sensor.MIN_SENSITIVITY, '550')
        self.value_test(Sensor.MAX_SENSITIVITY, '875')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '20')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '35')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '20')

    def test_H2S_AE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/H2S-AE.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'H2S-AE')
        self.value_test(Sensor.ALIAS, 'H2S-AE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, None)
        self.value_test(Sensor.DRIFT_INTERVAL, None)
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '2000')
        self.value_test(Sensor.ZERO_CURRENT, '< ±3')
        self.value_test(Sensor.OVERGAS_LIMIT, '10000')
        self.value_test(Sensor.MIN_SENSITIVITY, '65')
        self.value_test(Sensor.MAX_SENSITIVITY, '110')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '400')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '25')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '400')

    def test_H2S_A4(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/H2S-A4.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'H2S-A4')
        self.value_test(Sensor.ALIAS, 'H2S-A4')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '20')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '50')
        self.value_test(Sensor.ZERO_CURRENT, '-250 to 100')
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '1400')
        self.value_test(Sensor.MAX_SENSITIVITY, '1850')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '2')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '45')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '2')

    def test_H2_AF(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/H2-AF.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'H2-AF')
        self.value_test(Sensor.ALIAS, 'H2-AF')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, None)
        self.value_test(Sensor.DRIFT_INTERVAL, None)
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Hydrogen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.7')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '2000')
        self.value_test(Sensor.ZERO_CURRENT, '± 15')
        self.value_test(Sensor.OVERGAS_LIMIT, '5000')
        self.value_test(Sensor.MIN_SENSITIVITY, '10')
        self.value_test(Sensor.MAX_SENSITIVITY, '25')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '400')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '45')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '400')

    def test_ETO_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/ETO-A1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'ETO-A1')
        self.value_test(Sensor.ALIAS, 'ETO-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, '300')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, None)
        self.value_test(Sensor.DRIFT_INTERVAL, None)
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Ethylene Oxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'EtO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '± 0.6')
        self.value_test(Sensor.OVERGAS_LIMIT, '200')
        self.value_test(Sensor.MIN_SENSITIVITY, '2000')
        self.value_test(Sensor.MAX_SENSITIVITY, '3200')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '20')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '150')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '20')

    def test_CO_AX(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/COAX.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'CO-AX')
        self.value_test(Sensor.ALIAS, 'CO-AX')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '6')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '2000')
        self.value_test(Sensor.ZERO_CURRENT, '< ± 3')
        self.value_test(Sensor.OVERGAS_LIMIT, '4000')
        self.value_test(Sensor.MIN_SENSITIVITY, '55')
        self.value_test(Sensor.MAX_SENSITIVITY, '100')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '400')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '400')

    def test_CO_AF(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/COAF.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'CO-AF')
        self.value_test(Sensor.ALIAS, 'CO-AF')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '8')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '5000')
        self.value_test(Sensor.ZERO_CURRENT, '-5 to +4')
        self.value_test(Sensor.OVERGAS_LIMIT, '10000')
        self.value_test(Sensor.MIN_SENSITIVITY, '55')
        self.value_test(Sensor.MAX_SENSITIVITY, '90')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '400')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '25')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '400')

    def test_CO_AE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/COAE.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'CO-AE')
        self.value_test(Sensor.ALIAS, 'CO-AE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '1')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '10000')
        self.value_test(Sensor.ZERO_CURRENT, '< ± 20')
        self.value_test(Sensor.OVERGAS_LIMIT, '100000')
        self.value_test(Sensor.MIN_SENSITIVITY, '10')
        self.value_test(Sensor.MAX_SENSITIVITY, '25')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '2000')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '50')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '2000')

    def test_CO_A4(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/COA4.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'CO-A4')
        self.value_test(Sensor.ALIAS, 'CO-A4')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '36')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '500')
        self.value_test(Sensor.ZERO_CURRENT, '-100 to +10')
        self.value_test(Sensor.OVERGAS_LIMIT, '2000')
        self.value_test(Sensor.MIN_SENSITIVITY, '220')
        self.value_test(Sensor.MAX_SENSITIVITY, '375')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '2')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '20')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '10')

    def test_COH_A2(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/CO-H2S.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'COH-A2')
        self.value_test(Sensor.ALIAS, 'COH-A2')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '4')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-30')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '10')
        self.value_test(Sensor.MAX_LOAD, '47')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '4')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 2)
        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1000')
        self.value_test(Sensor.ZERO_CURRENT, '-3 to +3.5')
        self.value_test(Sensor.OVERGAS_LIMIT, '5000')
        self.value_test(Sensor.MIN_SENSITIVITY, '50')
        self.value_test(Sensor.MAX_SENSITIVITY, '100')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '400')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '35')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '400')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide', gas_number=2)
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S', gas_number=2)
        self.value_test(Sensor.UNITS, 'ppm', gas_number=2)
        self.value_test(Sensor.RESOLUTION, '0.1', gas_number=2)
        self.value_test(Sensor.MIN_READING, '0', gas_number=2)
        self.value_test(Sensor.MAX_READING, '100', gas_number=2)
        self.value_test(Sensor.ZERO_CURRENT, '± 0.25', gas_number=2)
        self.value_test(Sensor.OVERGAS_LIMIT, '200', gas_number=2)
        self.value_test(Sensor.MIN_SENSITIVITY, '450', gas_number=2)
        self.value_test(Sensor.MAX_SENSITIVITY, '1000', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_CONC, '20', gas_number=2)
        self.value_test(Sensor.T_TEST, 't90', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE, '30', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_END, '20', gas_number=2)

    def test_CL2_A1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/alphasense/CL2A1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Alphasense')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, 'CL2-A1')
        self.value_test(Sensor.ALIAS, 'CL2-A1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.2')
        self.value_test(Sensor.HEIGHT, '16.5')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '6')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '80')
        self.value_test(Sensor.MAX_PRESSURE, '120')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '33')
        self.value_test(Sensor.MAX_LOAD, '33')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '12')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_COUNT, 1)
        self.value_test(Sensor.GAS_NAME, 'Chlorine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'Cl2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.02')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '20')
        self.value_test(Sensor.ZERO_CURRENT, '± 0.4')
        self.value_test(Sensor.OVERGAS_LIMIT, '50')
        self.value_test(Sensor.MIN_SENSITIVITY, '-350')
        self.value_test(Sensor.MAX_SENSITIVITY, '-750')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, '10')
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, '0')
        self.value_test(Sensor.T_TEST_RESPONSE_END, '10')


if __name__ == '__main__':
    unittest.main()
