import unittest
import subprocess
import json
from collections import OrderedDict

from pdfscraper.models.sensor import Sensor
from pdfscraper.tests import test_utils


class TestSensoric(unittest.TestCase):

    def setUp(self):
        self.data = OrderedDict()
        self.incorrect_values = OrderedDict()

        test_utils.setUp(self.data, self.incorrect_values)

    def tearDown(self):
        test_utils.tearDown(self.data, self.incorrect_values)
        test_utils.display_result(self.incorrect_values)

        self.data.clear()
        self.incorrect_values.clear()

    def value_test(self, key, value, gas_number=1):
        test_utils.value_test(self.data, self.incorrect_values, key, value, gas_number)

    # def test_THT_3E(self):
    #     # This pdf is an outlier as it has small text from left over diagrams all over the place and can't be parser easily
    #     self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/tht3e.pdf')

    #     self.value_test(Sensor.MANUFACTURER, 'Sensoric')
    #     self.value_test(Sensor.TECHNOLOGY, 'EC')
    #     self.value_test(Sensor.PART_NUMBER, '2345-034-14049')
    #     self.value_test(Sensor.ALIAS, 'THT 3E 50')
    #     self.value_test(Sensor.ACTIVE, True)
    #     self.value_test(Sensor.DATASHEET_REV, None)

    #     self.value_test(Sensor.DIAMETER, '20.4')
    #     self.value_test(Sensor.HEIGHT, '16.6')
    #     self.value_test(Sensor.PIN_COUNT, '3')
    #     self.value_test(Sensor.PIN_LENGTH, '4.3')
    #     self.value_test(Sensor.WEIGHT, '6.2')

    #     self.value_test(Sensor.MIN_TEMP, '-10')
    #     self.value_test(Sensor.MAX_TEMP, '40')
    #     self.value_test(Sensor.MIN_PRESSURE, '91.1925')
    #     self.value_test(Sensor.MAX_PRESSURE, '111.458')
    #     self.value_test(Sensor.MIN_HUMIDITY, '15')
    #     self.value_test(Sensor.MAX_HUMIDITY, '90')

    #     self.value_test(Sensor.MIN_LOAD, '33')
    #     self.value_test(Sensor.MAX_LOAD, '33')
    #     self.value_test(Sensor.BIAS, '150')
    #     self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
    #     self.value_test(Sensor.DRIFT_INTERVAL, '6')
    #     self.value_test(Sensor.EXPECTED_LIFE, '18')
    #     self.value_test(Sensor.WARRANTY, '12')

    #     self.value_test(Sensor.GAS_NAME, 'Tetrahydrothiophene')
    #     self.value_test(Sensor.GAS_EMPIRICAL, 'C4H8S')
    #     self.value_test(Sensor.UNITS, 'mg/m^3')
    #     self.value_test(Sensor.RESOLUTION, None)
    #     self.value_test(Sensor.MIN_READING, '0')
    #     self.value_test(Sensor.MAX_READING, '50')
    #     self.value_test(Sensor.ZERO_CURRENT, '±200')
    #     self.value_test(Sensor.OVERGAS_LIMIT, None)
    #     self.value_test(Sensor.MIN_SENSITIVITY, '90')
    #     self.value_test(Sensor.MAX_SENSITIVITY, '190')
    #     self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
    #     self.value_test(Sensor.SENSITIVITY_CONC, None)
    #     self.value_test(Sensor.T_TEST, 't90')
    #     self.value_test(Sensor.T_TEST_RESPONSE, '30')
    #     self.value_test(Sensor.T_TEST_RESPONSE_START, None)
    #     self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_SeH2_3E_5_LT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/seh23e5flt.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '3035-337-30049')
        self.value_test(Sensor.ALIAS, 'SeH2 3E 5 LT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '4.5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '10')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '1500')
        self.value_test(Sensor.MAX_LOAD, '1500')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '10')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Selenide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'SeH2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.035')
        self.value_test(Sensor.MIN_READING, '0.05')
        self.value_test(Sensor.MAX_READING, '5')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, '10')
        self.value_test(Sensor.MIN_SENSITIVITY, '600')
        self.value_test(Sensor.MAX_SENSITIVITY, '1600')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_PH3_3E_5_LT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/ph33e5lt.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0635-337-30049')
        self.value_test(Sensor.ALIAS, 'PH3 3E 5 LT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '4.5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '10')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '1500')
        self.value_test(Sensor.MAX_LOAD, '1500')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Phosphine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'PH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.015')
        self.value_test(Sensor.MIN_READING, '0.03')
        self.value_test(Sensor.MAX_READING, '5')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, '20')
        self.value_test(Sensor.MIN_SENSITIVITY, '1700')
        self.value_test(Sensor.MAX_SENSITIVITY, '2700')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_PH3_3E_5_F_LT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/ph33e5flt.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0635-237-30049')
        self.value_test(Sensor.ALIAS, 'PH3 3E 5 F LT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '4.5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '10')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '1500')
        self.value_test(Sensor.MAX_LOAD, '1500')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Phosphine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'PH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.015')
        self.value_test(Sensor.MIN_READING, '0.03')
        self.value_test(Sensor.MAX_READING, '5')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, '20')
        self.value_test(Sensor.MIN_SENSITIVITY, '1500')
        self.value_test(Sensor.MAX_SENSITIVITY, '2500')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_O3_3E_1_F(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/o33e1f.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1531-231-30049')
        self.value_test(Sensor.ALIAS, 'O3 3E 1 F')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Ozone')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.03')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±10')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '-600')
        self.value_test(Sensor.MAX_SENSITIVITY, '-300')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_O3_3E_1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/o33e1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1531-031-30049')
        self.value_test(Sensor.ALIAS, 'O3 3E 1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Ozone')
        self.value_test(Sensor.GAS_EMPIRICAL, 'O3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.02')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '-2000')
        self.value_test(Sensor.MAX_SENSITIVITY, '-1000')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_NO_3E_100(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/no3e100.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1945-034-30049')
        self.value_test(Sensor.ALIAS, 'NO 3E 100')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-15')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '20')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, '200')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Nitrogen Oxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.7')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '±30')
        self.value_test(Sensor.OVERGAS_LIMIT, '500')
        self.value_test(Sensor.MIN_SENSITIVITY, '30')
        self.value_test(Sensor.MAX_SENSITIVITY, '60')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '20')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_NH3_3E_5000_SE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/nh33e5000se.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1858-932-30049')
        self.value_test(Sensor.ALIAS, 'NH3 3E 5000 SE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Ammonia')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '50')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '5000')
        self.value_test(Sensor.ZERO_CURRENT, '±100')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '2')
        self.value_test(Sensor.MAX_SENSITIVITY, '6')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_NH3_3E_1000_SE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/nh33e1000se.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1854-932-30049')
        self.value_test(Sensor.ALIAS, 'NH3 3E 1000 SE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Ammonia')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '12')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1000')
        self.value_test(Sensor.ZERO_CURRENT, '±40')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '4')
        self.value_test(Sensor.MAX_SENSITIVITY, '12')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_NH3_3E_1000(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/nh33e1000.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1854-031-30049')
        self.value_test(Sensor.ALIAS, 'NH3 3E 1000')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '5')

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, None)

        self.value_test(Sensor.GAS_NAME, 'Ammonia')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.015')
        self.value_test(Sensor.MIN_READING, '40')
        self.value_test(Sensor.MAX_READING, '1000')
        self.value_test(Sensor.ZERO_CURRENT, '±40')
        self.value_test(Sensor.OVERGAS_LIMIT, '5000')
        self.value_test(Sensor.MIN_SENSITIVITY, '3')
        self.value_test(Sensor.MAX_SENSITIVITY, '9')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '120')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_NH3_3E_500_SE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/nh33e500se.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1850-932-30049')
        self.value_test(Sensor.ALIAS, 'NH3 3E 500 SE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, '100')
        self.value_test(Sensor.MAX_LOAD, '100')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Ammonia')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, None)
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '500')
        self.value_test(Sensor.ZERO_CURRENT, '±100')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '20')
        self.value_test(Sensor.MAX_SENSITIVITY, '50')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_NH3_3E_100_SE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/nh33e100se.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1845-932-30049')
        self.value_test(Sensor.ALIAS, 'NH3 3E 100 SE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Ammonia')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '±100')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '100')
        self.value_test(Sensor.MAX_SENSITIVITY, '160')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_NH3_3E_100(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/nh33e100.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1845-031-30049')
        self.value_test(Sensor.ALIAS, 'NH3 3E 100')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Ammonia')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '2')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '±150')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '50')
        self.value_test(Sensor.MAX_SENSITIVITY, '130')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '120')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_HF_3E_10_SE(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/hf3e10se.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1336-932-30049')
        self.value_test(Sensor.ALIAS, 'HF 3E 10 SE')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '4.6')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Fluoride')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HF')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.15')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '10')
        self.value_test(Sensor.ZERO_CURRENT, '±30')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '-400')
        self.value_test(Sensor.MAX_SENSITIVITY, '-200')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_HCN_3E_30_F(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/hcn3e30f.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1639-231-30049')
        self.value_test(Sensor.ALIAS, 'HCN 3E 30 F')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Cyanide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HCN')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.2')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '30')
        self.value_test(Sensor.ZERO_CURRENT, '±15')
        self.value_test(Sensor.OVERGAS_LIMIT, '100')
        self.value_test(Sensor.MIN_SENSITIVITY, '45')
        self.value_test(Sensor.MAX_SENSITIVITY, '75')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '50')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_HCN_2E_30_F(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/hcn2e30f.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1639-221-30049')
        self.value_test(Sensor.ALIAS, 'HCN 2E 30 F')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '2')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Cyanide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HCN')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.2')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '30')
        self.value_test(Sensor.ZERO_CURRENT, '±5')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '15')
        self.value_test(Sensor.MAX_SENSITIVITY, '45')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_HCL_HBr_3E_30(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/hclhbr3e30.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1139-034-30049')
        self.value_test(Sensor.ALIAS, 'HCl/Hbr 3E 30')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, '200')
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '3')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Chloride')
        self.value_test(Sensor.GAS_EMPIRICAL, 'HCl')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.7')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '30')
        self.value_test(Sensor.ZERO_CURRENT, '±100')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '80')
        self.value_test(Sensor.MAX_SENSITIVITY, '200')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '70')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Bromide', gas_number=2)
        self.value_test(Sensor.GAS_EMPIRICAL, 'HBr', gas_number=2)
        self.value_test(Sensor.UNITS, 'ppm', gas_number=2)
        self.value_test(Sensor.RESOLUTION, '0.7', gas_number=2)
        self.value_test(Sensor.MIN_READING, '0', gas_number=2)
        self.value_test(Sensor.MAX_READING, '30', gas_number=2)
        self.value_test(Sensor.ZERO_CURRENT, '±100', gas_number=2)
        self.value_test(Sensor.OVERGAS_LIMIT, None, gas_number=2)
        self.value_test(Sensor.MIN_SENSITIVITY, '80', gas_number=2)
        self.value_test(Sensor.MAX_SENSITIVITY, '200', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm', gas_number=2)
        self.value_test(Sensor.SENSITIVITY_CONC, None, gas_number=2)
        self.value_test(Sensor.T_TEST, 't90', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE, '70', gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_START, None, gas_number=2)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None, gas_number=2)

    def test_H2_3E_4PERCENT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/h23e4.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0364-034-30049')
        self.value_test(Sensor.ALIAS, 'H2 3E 4%')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '18')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '100')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '40000')
        self.value_test(Sensor.ZERO_CURRENT, '±100')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '0.5')
        self.value_test(Sensor.MAX_SENSITIVITY, '1.5')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_H2_3E_1PERCENT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/h23e1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0361-034-30049')
        self.value_test(Sensor.ALIAS, 'H2 3E 1%')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '18')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '20')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '10000')
        self.value_test(Sensor.ZERO_CURRENT, '±250')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '5')
        self.value_test(Sensor.MAX_SENSITIVITY, '15')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '70')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_H2S_3E_100_S(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/h2s3e100s.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0145-134-30049')
        self.value_test(Sensor.ALIAS, 'H2S 3E 100 S')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '48')
        self.value_test(Sensor.WARRANTY, '24')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.3')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '±200')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '600')
        self.value_test(Sensor.MAX_SENSITIVITY, '900')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_H2S_3E_100(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/h2s3e100.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0145-034-30049')
        self.value_test(Sensor.ALIAS, 'H2S 3E 100')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '48')
        self.value_test(Sensor.WARRANTY, '24')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.3')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '100')
        self.value_test(Sensor.ZERO_CURRENT, '±200')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '600')
        self.value_test(Sensor.MAX_SENSITIVITY, '900')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_H2S_2E_50_S(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/h2s2e50s.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0141-124-30049')
        self.value_test(Sensor.ALIAS, 'H2S 2E 50 S')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '2')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '48')
        self.value_test(Sensor.WARRANTY, '24')

        self.value_test(Sensor.GAS_NAME, 'Hydrogen Sulfide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'H2S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.7')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '50')
        self.value_test(Sensor.ZERO_CURRENT, '±200')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '300')
        self.value_test(Sensor.MAX_SENSITIVITY, '460')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_F2_3E_1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/f23e1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1431-031-30049')
        self.value_test(Sensor.ALIAS, 'F2 3E 1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-10')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Fluorine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'F2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.02')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '-1300')
        self.value_test(Sensor.MAX_SENSITIVITY, '-700')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '80')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_COCl2_3E_1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/cocl23e1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '1731-031-14049')
        self.value_test(Sensor.ALIAS, 'COCl2 3E 1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '12')
        self.value_test(Sensor.WARRANTY, '7')

        self.value_test(Sensor.GAS_NAME, 'Phosgene')
        self.value_test(Sensor.GAS_EMPIRICAL, 'COCl2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.02')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±10')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '500')
        self.value_test(Sensor.MAX_SENSITIVITY, '800')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '120')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_CO_3E_300(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/co3e300.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0248-034-30049')
        self.value_test(Sensor.ALIAS, 'CO 3E 300')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-40')
        self.value_test(Sensor.MAX_TEMP, '50')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '48')
        self.value_test(Sensor.WARRANTY, '24')

        self.value_test(Sensor.GAS_NAME, 'Carbon Monoxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CO')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '3')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '500')
        self.value_test(Sensor.ZERO_CURRENT, '150')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '50')
        self.value_test(Sensor.MAX_SENSITIVITY, '90')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_ClO2_3E_1_O(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/clo23e1o.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '2731-331-30049')
        self.value_test(Sensor.ALIAS, 'ClO2 3E 1 O')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Chlorine Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'ClO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.03')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±15')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '-800')
        self.value_test(Sensor.MAX_SENSITIVITY, '-400')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '120')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_Cl2_3E_50(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/cl23e50.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0441-032-30049')
        self.value_test(Sensor.ALIAS, 'Cl2 3E 50')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Chlorine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'Cl2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.05')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '5')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, '50')
        self.value_test(Sensor.MIN_SENSITIVITY, '-650')
        self.value_test(Sensor.MAX_SENSITIVITY, '-250')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_Cl2_3E_10(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/cl23e10.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0436-032-30049')
        self.value_test(Sensor.ALIAS, 'Cl2 3E 10')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Chlorine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'Cl2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.05')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '5')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, '10')
        self.value_test(Sensor.MIN_SENSITIVITY, '-650')
        self.value_test(Sensor.MAX_SENSITIVITY, '-250')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_B2H6_3E_1_LT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/b2h63e1lt.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0831-337-30049')
        self.value_test(Sensor.ALIAS, 'B2H6 3E 1 LT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '4.5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '10')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '1500')
        self.value_test(Sensor.MAX_LOAD, '1500')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '10')

        self.value_test(Sensor.GAS_NAME, 'Diborane')
        self.value_test(Sensor.GAS_EMPIRICAL, 'B2H6')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.015')
        self.value_test(Sensor.MIN_READING, '0.03')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, '10')
        self.value_test(Sensor.MIN_SENSITIVITY, '1700')
        self.value_test(Sensor.MAX_SENSITIVITY, '2700')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_AsH3_3E_1_LT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/ash33e1lt.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0731-337-30049')
        self.value_test(Sensor.ALIAS, 'AsH3 3E 1 LT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '4.5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '10')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '1500')
        self.value_test(Sensor.MAX_LOAD, '1500')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '10')

        self.value_test(Sensor.GAS_NAME, 'Arsine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'AsH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.015')
        self.value_test(Sensor.MIN_READING, '0.03')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, '20')
        self.value_test(Sensor.MIN_SENSITIVITY, '950')
        self.value_test(Sensor.MAX_SENSITIVITY, '1850')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_AsH3_3E_1_F_LT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/ash33e1flt.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0731-237-30049')
        self.value_test(Sensor.ALIAS, 'AsH3 3E 1 F LT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '4.5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '10')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '1500')
        self.value_test(Sensor.MAX_LOAD, '1500')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '10')

        self.value_test(Sensor.GAS_NAME, 'Arsine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'AsH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.015')
        self.value_test(Sensor.MIN_READING, '0.03')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, '20')
        self.value_test(Sensor.MIN_SENSITIVITY, '950')
        self.value_test(Sensor.MAX_SENSITIVITY, '1850')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_AsH3_2E_1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/ash32e1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0731-021-30049')
        self.value_test(Sensor.ALIAS, 'AsH3 2E 1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '2')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '20')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '18')
        self.value_test(Sensor.WARRANTY, '10')

        self.value_test(Sensor.GAS_NAME, 'Arsine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'AsH3')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.02')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '0.5')
        self.value_test(Sensor.ZERO_CURRENT, '±10')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '340')
        self.value_test(Sensor.MAX_SENSITIVITY, '800')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_N2H4_2E_1(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/n2h42e1.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '2131-021-30049')
        self.value_test(Sensor.ALIAS, 'N2H4 2E 1')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '2')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-10')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '20')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '12')
        self.value_test(Sensor.WARRANTY, '10')

        self.value_test(Sensor.GAS_NAME, 'Hydrazine')
        self.value_test(Sensor.GAS_EMPIRICAL, 'N2H4')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.01')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '1')
        self.value_test(Sensor.ZERO_CURRENT, '±15')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '900')
        self.value_test(Sensor.MAX_SENSITIVITY, '1500')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '120')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_SiH4_3E_50_LT(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/sih43e50lt.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '0941-337-30049')
        self.value_test(Sensor.ALIAS, 'SiH4 3E 50 LT')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, '4.5')

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, '91.1925')
        self.value_test(Sensor.MAX_PRESSURE, '111.458')
        self.value_test(Sensor.MIN_HUMIDITY, '10')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, '1500')
        self.value_test(Sensor.MAX_LOAD, '1500')
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '6')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Silane')
        self.value_test(Sensor.GAS_EMPIRICAL, 'SiH4')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.5')
        self.value_test(Sensor.MIN_READING, '1')
        self.value_test(Sensor.MAX_READING, '50')
        self.value_test(Sensor.ZERO_CURRENT, '±25')
        self.value_test(Sensor.OVERGAS_LIMIT, '50')
        self.value_test(Sensor.MIN_SENSITIVITY, '60')
        self.value_test(Sensor.MAX_SENSITIVITY, '200')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '60')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_TBM_2E_50(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/tbm2e.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '2441-021-04049')
        self.value_test(Sensor.ALIAS, 'TBM 2E 50')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '2')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-10')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '10')
        self.value_test(Sensor.MAX_HUMIDITY, '95')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '10')
        self.value_test(Sensor.DRIFT_INTERVAL, '10')
        self.value_test(Sensor.EXPECTED_LIFE, '12')
        self.value_test(Sensor.WARRANTY, '9')

        self.value_test(Sensor.GAS_NAME, 'Mercaptan')
        self.value_test(Sensor.GAS_EMPIRICAL, 'CH4S')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.14')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '14')
        self.value_test(Sensor.ZERO_CURRENT, '±4')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '3')
        self.value_test(Sensor.MAX_SENSITIVITY, '8')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '90')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)

    def test_NO2_3E_50(self):
        self.data = test_utils.run_scraper('pdfscraper/tests/datasheets/sensoric/no23e50.pdf')

        self.value_test(Sensor.MANUFACTURER, 'Sensoric')
        self.value_test(Sensor.TECHNOLOGY, 'EC')
        self.value_test(Sensor.PART_NUMBER, '2241-032-30049')
        self.value_test(Sensor.ALIAS, 'NO2 3E 50')
        self.value_test(Sensor.ACTIVE, True)
        self.value_test(Sensor.DATASHEET_REV, None)

        self.value_test(Sensor.DIAMETER, '20.4')
        self.value_test(Sensor.HEIGHT, '16.6')
        self.value_test(Sensor.PIN_COUNT, '3')
        self.value_test(Sensor.PIN_LENGTH, '4.3')
        self.value_test(Sensor.WEIGHT, None)

        self.value_test(Sensor.MIN_TEMP, '-20')
        self.value_test(Sensor.MAX_TEMP, '40')
        self.value_test(Sensor.MIN_PRESSURE, None)
        self.value_test(Sensor.MAX_PRESSURE, None)
        self.value_test(Sensor.MIN_HUMIDITY, '15')
        self.value_test(Sensor.MAX_HUMIDITY, '90')

        self.value_test(Sensor.MIN_LOAD, None)
        self.value_test(Sensor.MAX_LOAD, None)
        self.value_test(Sensor.BIAS, None)
        self.value_test(Sensor.MAX_SIGNAL_DRIFT, '5')
        self.value_test(Sensor.DRIFT_INTERVAL, '1')
        self.value_test(Sensor.EXPECTED_LIFE, '24')
        self.value_test(Sensor.WARRANTY, '12')

        self.value_test(Sensor.GAS_NAME, 'Nitrogen Dioxide')
        self.value_test(Sensor.GAS_EMPIRICAL, 'NO2')
        self.value_test(Sensor.UNITS, 'ppm')
        self.value_test(Sensor.RESOLUTION, '0.1')
        self.value_test(Sensor.MIN_READING, '0')
        self.value_test(Sensor.MAX_READING, '50')
        self.value_test(Sensor.ZERO_CURRENT, '±20')
        self.value_test(Sensor.OVERGAS_LIMIT, None)
        self.value_test(Sensor.MIN_SENSITIVITY, '-240')
        self.value_test(Sensor.MAX_SENSITIVITY, '-160')
        self.value_test(Sensor.SENSITIVITY_RATIO, 'nA/ppm')
        self.value_test(Sensor.SENSITIVITY_CONC, None)
        self.value_test(Sensor.T_TEST, 't90')
        self.value_test(Sensor.T_TEST_RESPONSE, '30')
        self.value_test(Sensor.T_TEST_RESPONSE_START, None)
        self.value_test(Sensor.T_TEST_RESPONSE_END, None)


if __name__ == '__main__':
    unittest.main()
